version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          store_artifacts: true
          post-steps:
            - run: npm run merge_report
            - run: npm run marge_report
            - store_artifacts:
                path: cypress/reports/