version: 2.1
orbs:
  cypress: cypress-io/cypress@1
  jira: circleci/jira@1.2.2

workflows:
  build:
    jobs:
      - cypress/run:
          store_artifacts: true
          post-steps:
            - run:
                command: |
                  npm run merge_report
                  npm run marge_report
                when: always
            - store_artifacts:
                path: cypress/reports/
            - jira/notify:
                job_type: deployment
