version: 2.1
orbs:
  cypress: cypress-io/cypress@1

workflows:
  build:
    jobs:
      - cypress/run:
          post-steps:
            - run:
                command: |
                  npm run merge_report
                  npm run marge_report
                when: always
            - store_artifacts:
                path: cypress/reports/
